name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [20]
        test-suite: [check, vitest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.*
      - run: pnpm dev:setup

      - name: Run checks
        run: pnpm tsc:check && pnpm lint && pnpm lint:format
        if: matrix.test-suite == 'check'

      - name: Run tests
        run: pnpm vitest:run
        if: matrix.test-suite == 'vitest'
